import NuggetBox from "./components/NuggetBox";
import {SimpleGrid, Text} from "@chakra-ui/react";
import Para from "./components/Para";
import * as React from "react";

export default function Features() {
    return (
        <SimpleGrid columns={[2, 2, 3]} spacing={2} mt={5} px={2}>
            {/*<NuggetBox>*/}
            {/*    <Text fontSize="l">*/}
            {/*    </Text>*/}
            {/*</NuggetBox>*/}
            {/*<NuggetBox>*/}

            {/*</NuggetBox>*/}
            <NuggetBox noCenter>
                <Text fontSize="l">
                    <Para textAlign={'center'}>
                        <b>What makes our project different:</b>
                    </Para>
                    <p>
                        1. We’re using Polygon for low gas fees.
                    </p>
                    {/*<p> 2. We have a unique way of growing our community by using a “share to mint” concept.*/}
                    {/*</p>*/}
                    <p> 2. Our NFTs are about friendship and sharing.
                    </p>
                    <p>
                        3. Our NFTs will change over time, kind of like a chronicle of the journey of two
                        friends.
                    </p>
                </Text>
            </NuggetBox>
            <NuggetBox>
                <Text fontSize="l">
                    <Para>
                        <b>Layered On-chain Generative Art. </b>
                    </Para>
                    The Hug NFTs are generated by combining different unique elements,
                    for example, different types of people, different clothes,
                    different colors and patterns, settings and backgrounds. The NFTs
                    are generative art with unpredictable randomness.
                    When you press the "mint" button YOU are creating a unique piece of art via a blockchain
                    smart contract.
                    {/*The unique elements of the Hug NFTs are mixed and matched by the blockchain, */}
                    {/*just like our collection of friends are created in real life!*/}
                </Text>
            </NuggetBox>
            <NuggetBox>
                <Text fontSize="l">
                    <Para>
                        <b>Sending love on-chain</b>
                    </Para>
                    Remember the joy of receiving a friendship card in the mail? The
                    Hug NFT strives to bring this same experience to the web 3.0
                </Text>
            </NuggetBox>
        </SimpleGrid>
    )
}
